colorScheme = "fire"
defaultAppearance = "light"
autoSwitchAppearance = false
footer.showCopyright = false
footer.showThemeAttribution = false
list.showSummary = true
list.groupByYear = false
homepage.layout = "custom"
homepage.showRecent = true
header.logo = "logo.png"
header.showTitle = false
